### PR TITLE
🔖 3.1.0: Simple QoL update for file structure (+ debug improvements)

### PR DESCRIPTION
**Pull request by hyd3rs**
- Updated discord.js to v14.9.0
- Separate command interactions into distinct categories
- Improved error debug by adding a database heartbeat and "last connection" sequence

### CODE REVIEW

**Comment by islemci** [comment]
Just curious, are you still working on this project? @daniwasonline

**Comment by hyd3rs** [comment]
Right now, no - I don't really have the need for it at the moment. I'll probably come back to this in the future and do a clean-up and upgrade for funsies, though! :smile:

(If you have time and want to take over, feel free to fork it or I can give you maintainer access! It would be fun to see this go on, even in spirit with just the idea lol)

**Comment by islemci** [comment]
It would be nice to develop this project, but I'm still focused on school and I haven't been coding for a long time. Maybe one day I'll have the chance to support you!

**Comment by hyd3rs** [comment]
Aye, no worries at all! Again, it's very likely that I'll come back and work on this again in the future - I just haven't found the time or need for working on this since May.

Good luck on your studies! stay in school lmao

**Pull request merged**
